[[plugins]]
package = "netlify-plugin-csp-generator"

  [plugins.inputs]
  buildDir = "dist"

  [plugins.inputs.policies]
    generateForAllFiles = true
    defaultSrc = "'self'"
    styleSrc = "'unsafe-hashes'"